---
output:
  html_document:
    keep_md: yes
params: 
    set_title: !r paste("Kontroll av PJS-data for:", purpose, aar)
title: "`r params$set_title`"
---
```{r set-options, echo=FALSE, cache=FALSE, clean=FALSE}
options(width = 1000)
```

```{r setup, include=FALSE}

# Attach packages
library(NVIbatch)
use_pkg(pkg = c("dplyr", "tidyr", "knitr", "kableExtra", "htmltools"))
use_NVIverse(pkg = c("NVIdb", "OKcheck"))

# Global variables
# For use in filenames
today <- format(Sys.Date(), "%Y%m%d")

# Import support data
# Translation table for PJS-codes
PJS_codes_2_text <- NVIdb::read_PJS_codes_2_text()

# Table with accepted code combinations per OK-program (purpose)
accepted_codes <- openxlsx::read.xlsx(xlsxFile = paste0(NVIdb::set_dir_NVI("OKprogrammer"),
                                                                "OKstatistikkApp/Stottedata/Kontrolltabeller_PJS_", 
                                                                aar, 
                                                                ".xlsx"),
                                              detectDates = TRUE)

accepted_codes <- subset(accepted_codes, accepted_codes$program == purpose)

knitr::opts_chunk$set(echo=TRUE)
```

```{r, include = FALSE}
## Kontroll av PJS-data for: `r purpose` `r aar` per `r format(Sys.Date(), "%d.%m.%Y")`

```

<!-- Tabell I-1. Saker som ikke er avsluttet -->
```{r child=system.file('templates', "check_avsluttet.Rmd", package = "OKcheck")}
```

<!-- Tabell P-1. Saker med feil eller manglende art -->
```{r echo = FALSE}
# All combinations of variables that should be checked
variable_names <- c("artkode", "driftsformkode", "metodekode", "res_analyttkode", "konkl_analyttkode")
combinations <- unique(accepted_codes[, c("var1", "var2", "var3")])
combinations <- subset(combinations, 
                       combinations$var1 %in% variable_names &
                         (is.na(combinations$var2) | combinations$var2 %in% variable_names) &
                         (is.na(combinations$var3) | combinations$var3 %in% variable_names))

# Relation between column name and pJS-type as used by NVIdb::add_PJS_code_description below 
PJS_codetype <- c("ansvarlig_seksjon" = "seksjon", 
                  "hensiktkode" = "hensikt",
                  "artkode" = "art", "driftsformkode" = "driftsform", 
                  "provetypekode" = "provetype", "provematerialekode" = "provemateriale",
                  "metodekode" = "metode", 
                  "konkl_kjennelsekode" = "kjennelse", "konkl_analyttkode" = "analytt", 
                  "res_kjennelsekode" = "kjennelse", "res_analyttkode" = "analytt",
                  "konkl_type" = "konkl_type", "eier_lokalitetstype" = "registertype")


list_with_checks <- vector("list", length = dim(combinations)[1])
# run for each combination of variables that should be checked
for (i in c(1:dim(combinations)[1])) {
  # Identify the combination of variables to check
  code_variable <- as.vector(t(combinations[i,]))
  code_variable <- subset(code_variable, !is.na(code_variable))
  
  # Find the accepted codes for the current combination of variables
  code_2_accept <- find_accepted_code(data = accepted_codes, purpose = purpose, code_variable = code_variable) 
  
  # Check is only done when values in code_2_accept
  if (length(code_2_accept) > 0) {
    # transform code_2_accept to regular expressions
    code_2_accept <- paste0("^", code_2_accept)
    code_2_accept <- gsub(pattern = "%", replacement = "[[:digit:]]*", x = code_2_accept, fixed = TRUE)
    
    # Identifies all variables in the index taking into consideration the PJS-levels of the code_variable(s)
    index <- c("aar", "ansvarlig_seksjon", "innsendelsenr")
    for (k in 1:length(code_variable)) {
      index <- union(index,
                     NVIdb::PJS_levels[which(NVIdb::PJS_levels[1:10, which(NVIdb::PJS_levels[which(NVIdb::PJS_levels$variable == code_variable[k]), ] == 1)] == 1), "variable"])
    }
    # Keeps only variables that exist in PJSdata. Necessary as resnr will not be in PJSdata.
    index <- base::intersect(index, colnames(PJSdata))
    
    # Combine the codes that should be checked into one variable
    ktr <- PJSdata[, c("saksnr", index, "hensiktkode", code_variable)] 
    ktr <- unique(ktr)
    ktr$combined_codes <- apply(ktr[, c("hensiktkode", code_variable)], 1, FUN = paste, collapse = "-")
    
    # Find records deviating from accepted code values  
    ktr <- ktr %>%
      dplyr::rowwise() %>%
      dplyr::mutate(accepted = max(unlist(lapply(code_2_accept, grep, x = combined_codes)),0)) %>%
      dplyr::filter(accepted == 0) %>%
      dplyr::select(-c(combined_codes, accepted)) %>%
      dplyr::distinct() %>%
      dplyr::arrange(across(all_of(index)))
    
    # if prove-level, put all records within same saksnr and code_variable on a single row
    # all provenr per sak into one variable
    # All provenr for one sak on one row
    if (base::setequal(index, c("aar", "ansvarlig_seksjon", "innsendelsenr", "provenr"))) {
      ktr <- ktr %>%
        dplyr::arrange(across(all_of(c("aar", "ansvarlig_seksjon", "innsendelsenr", code_variable)))) %>%
        tidyr::pivot_wider(id_cols = all_of(c("aar", "ansvarlig_seksjon", "innsendelsenr", "saksnr",  "hensiktkode", code_variable)),
                           names_from = provenr,
                           values_from = provenr,
                           names_prefix = "p") %>%
        dplyr::rowwise() %>%
        # Combine all provenr into one variable
        dplyr::mutate(provenr = toString(c_across(starts_with("p")))) %>%
        # Keep all provenr and remove provenr with NA
        dplyr::mutate(provenr = gsub("NA, ", "", provenr)) %>%
        dplyr::mutate(provenr = trimws(provenr, "b", "[ ,NA]")) 
      
      ktr <- ktr[, c("saksnr", index, "hensiktkode", code_variable)]
      # ktr <- ktr[, c( "provenr", "hensiktkode", code_variable)]
    }
    
    ktr <- dplyr::select(ktr, -c(aar, ansvarlig_seksjon, innsendelsenr))
    
    # Add description text to PJS-codes
    for (j in c("hensiktkode", code_variable)) {
      if (j %in% names(PJS_codetype)) {
        ktr <- NVIdb::add_PJS_code_description(data = ktr,
                                               translation_table = PJS_codes_2_text, 
                                               PJS_variable_type = PJS_codetype[j],
                                               code_colname = j,
                                               new_column = sub("kode", "", j)) 
      }
    }

    # print_table
  } else { ktr <- data.frame()}
  
  heading <- paste("<br/> <br/>",   # &nbsp may be more general than <br/>
                   "<h4> Tabell P-1. Pr\u00F8ver der art er feil eller som mangler opplysning om arten </h4>",
                   "<h5> Ber om at korrekt art legges inn. </h5>")
  
  # # Print table and heading data to report, else don't print
  #   # WRITE DATA WHEN ROWS TO CHECK ----
  # # Output data if any cases need to be checked
  # if (dim(ktr)[1] > 0) {
  #   colnames(ktr) <- NVIdb::standardize_columns(data = ktr, property = "collabels")
  # 
    # print(knitr::kable(ktr, format = "html", caption = heading) %>%
    #   kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")))
   list_with_checks[i] <- print(knitr::kable(ktr, format = "html", caption = heading) %>%
      kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")))
  # }

  # list_with_checks[i] <- OKcheck::knit_table_if_data(data = ktr, heading = heading)
  # OKcheck::knit_table_if_data(data = ktr, heading = heading)
}
# htmltools::tagList(list_with_checks)
htmltools::knit_print.html(htmltools::tagList(list_with_checks))


```

<!-- Tabell P-1. Saker med feil eller manglende art -->
```{r child=system.file('templates', "check_art.Rmd", package = "OKcheck")}
```

<!-- Tabell K-1. Prover med konklusjonsanalytt som ikke er en del av programmet -->
```{r child=system.file('templates', "check_konkl_analytt.Rmd", package = "OKcheck")}
```

<!-- Tabell U-1. Undersokelser med resultatanalytt som ikke samsvarer med metoden -->
```{r child=system.file('templates', "check_metode_res_analytt.Rmd", package = "OKcheck")}
```

<!-- Tabell K-1. Saker med mer enn en sakskonklusjon for identiske saksanalytter -->
```{r child=system.file('templates', "check_doubble_sak_konkl.Rmd", package = "OKcheck")}
```

<!-- Tabell K-2. Sakskonklusjon uten tilsvarende provekonklusjon for minst en prove -->
```{r child=system.file('templates', "check_konkl_sak_u_prv.Rmd", package = "OKcheck")}
```

<!-- Tabell Kx-3. Positiv sakskonklusjon mangler når det er positiv provekonklusjon -->
```{r, include = FALSE}
kjennelsekode <- "020209"
analyttkode <- "01150101070103"
```

```{r child=system.file('templates', "check_konkl_sak_when_pos_prv.Rmd", package = "OKcheck")}
```

<!-- Tabell Kx-3. Positiv sakskonklusjon mangler nar det er positiv provekonklusjon -->
```{r, include = FALSE}
kjennelsekode <- "020209"
analyttkode <- "01190108"
```

```{r child=system.file('templates', "check_konkl_sak_when_pos_prv.Rmd", package = "OKcheck")}
```

<!-- Tabell K-4. Prover med mer enn en provekonklusjon for identiske proveanalytter -->
```{r child=system.file('templates', "check_doubble_prv_konkl.Rmd", package = "OKcheck")}
```

<!-- Tabell K-5. Prover med forelopig konklusjon -->
```{r child=system.file('templates', "check_forelopig_konkl.Rmd", package = "OKcheck")}
```

<!-- Tabell K-7. Positivt resultat mangler nar det er positiv provekonklusjon -->
```{r child=system.file('templates', "check_res_when_pos_prv.Rmd", package = "OKcheck")}
```

