---
output:
  html_document:
    theme: sandstone
params: 
    set_title: !r paste("Kontroll av PJS-data for:", purpose, aar)
title: "`r params$set_title`"
---
```{r set-options, echo=FALSE, cache=FALSE}
options(width = 1000)
```

```{r setup, include=FALSE}

    # set_title: "My Title!"

# "Kontroll av PJS-data for OK-programmer"
# title: Kontroll av PJS-data for: `r purpose` `r aar`
# author: "Seksjon for epidemiologi, Veterinærinstituttet"
#Load packages
library(dplyr)
library(tidyr)
# library(openxlsx)
# require("stringr")
library(knitr)
library(kableExtra)
# library(ggplot2)
# library(tidyr)
# library(gtools)
library(NVIdb)

# Global variables
#For use in filenames
today <- format(Sys.Date(), "%Y%m%d")
# domene <- sub("Rscripts","",dirname(rstudioapi::getSourceEditorContext()$path))

knitr::opts_chunk$set(echo=TRUE)
```


```{r, include = FALSE}
# Import support data
# Translation table for PJS-codes
PJS_codes_2_text <- NVIdb::read_PJS_codes_2_text()

## Kontroll av PJS-data for: `r purpose` `r aar`   

```


### Resultat av kontroll for manglende eller feil prøveopplysninger per `r format(Sys.Date(), "%d.%m.%Y")`   
```{r, echo = F}
# PRØVER MED MISSING ART

heading <- paste("<br/> <br/>",   # &nbsp may be more general than <br/>
                 "<h4> Tabell 1. Prøver som mangler opplysning om art eller der art er feil </h4>",
                 "<h5> Ber om at art legges inn. </h5>")

# Identify cases that need to be checked
ktr <- PJSdata %>%
  dplyr::select(saksnr, aar, ansvarlig_seksjon, innsendelsenr, provenr, artkode) %>%
  dplyr::filter(is.na(artkode)) %>%
  dplyr::arrange(aar, ansvarlig_seksjon, innsendelsenr, provenr) %>%
  dplyr::select(-c(aar, ansvarlig_seksjon, innsendelsenr)) %>%
  dplyr::distinct() %>%
  tidyr::pivot_wider(id_cols = c(saksnr, artkode),
                     names_from = provenr,
                     values_from = provenr,
                     names_prefix = "P") %>%
  dplyr::rowwise() %>%
  dplyr::mutate(provenr = toString(c_across(starts_with("P")))) %>%
  dplyr::mutate(provenr = gsub("NA, ", "", provenr)) %>%
  dplyr::mutate(provenr = trimws(provenr, "b", "[ ,NA]")) %>%
  dplyr::select(saksnr, provenr, artkode) %>%
  NVIdb::add_PJS_code_description(PJS_variable_type = c("art"),
                                  code_colname = c("artkode"),
                                  new_column = c("art")) 

# Remove heading if no data to report
OKcheck::write_data_for_checking(data = ktr, heading = heading)
#if (dim(ktr)[1] == 0) {
#  heading <- ""
#}
#knitr::asis_output(heading) # placed here as kitr::asis_output cannot be within a for-loop or an if-clause

# # Output ktr if any cases need to be checked
#if (dim(ktr)[1] > 0) {
#  colnames(ktr) <- NVIdb::standardize_columns(ktr, property = "collabels")
  
#  knitr::kable(ktr) %>%
#    kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
#}
```
